AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation stack for Learn-Easy - Orchestrates all resources'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be created
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs (at least 2 for multi-AZ)
  
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: Database instance class
  
  DBUsername:
    Type: String
    Default: postgres
    Description: Database master username
    NoEcho: true
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database master password
    MinLength: 8
  
  S3BucketName:
    Type: String
    Description: S3 bucket name for uploads (must be globally unique)
  
  AdminPassword:
    Type: String
    NoEcho: true
    Description: Admin panel password
    MinLength: 8
  
  SessionSecret:
    Type: String
    NoEcho: true
    Description: Session secret for authentication
    MinLength: 16

Resources:
  # Database Stack
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: database.yml
      Parameters:
        DBInstanceIdentifier: !Sub 'learn-easy-${Environment}-db'
        DBName: learn_easy
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBInstanceClass: !Ref DBInstanceClass
        VpcId: !Ref VpcId
        SubnetIds: !Ref SubnetIds

  # S3 Storage Stack
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3-storage.yml
      Parameters:
        BucketName: !Ref S3BucketName
        Environment: !Ref Environment

  # ECS Cluster (simplified - you can expand this)
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'learn-easy-${Environment}-cluster'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      Tags:
        - Key: Name
          Value: !Sub 'Learn-Easy-${Environment}-Cluster'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DatabaseEndpoint:
    Description: RDS database endpoint
    Value: !GetAtt DatabaseStack.Outputs.DBEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'
  
  DatabaseURL:
    Description: Database connection URL
    Value: !GetAtt DatabaseStack.Outputs.DatabaseURL
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseURL'
  
  S3BucketName:
    Description: S3 bucket for uploads
    Value: !GetAtt S3Stack.Outputs.BucketName
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'
  
  AppRoleArn:
    Description: IAM role for application
    Value: !GetAtt S3Stack.Outputs.AppRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-AppRoleArn'
  
  ECSClusterName:
    Description: ECS cluster name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${AWS::StackName}-ECSClusterName'
