AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for Learn-Easy file uploads'

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket (must be globally unique)
  
  Environment:
    Type: String
    Default: production
    Description: Environment name

Resources:
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Name
          Value: Learn-Easy-Uploads
        - Key: Environment
          Value: !Ref Environment

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-learn-easy-app-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: S3UploadsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${UploadsBucket}/*'
                  - !GetAtt UploadsBucket.Arn

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: AppRole
    Properties:
      Bucket: !Ref UploadsBucket
      PolicyDocument:
        Statement:
          - Sid: AllowAppAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt AppRole.Arn
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub '${UploadsBucket}/*'
              - !GetAtt UploadsBucket.Arn

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref UploadsBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt UploadsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  
  AppRoleArn:
    Description: IAM role ARN for application
    Value: !GetAtt AppRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AppRoleArn'
